/**
 * Brain structure registry.
 *
 * This module is the single source of truth for Brain Mode navigation.
 * It is built from the actual BodyParts3D atlas + the KYP normalization
 * overrides — it does NOT fabricate any structures that don't exist in
 * the source data.
 *
 * Architecture:
 *
 *   Atlas (atlas.json) ─────────────┐
 *   KYP normalization overrides ────┤
 *                                  ↓
 *   Brain structure registry (this file)
 *     - brainStructureGroups (data-driven; only groups with ≥1 real concept)
 *     - brainPresets (views: Whole Brain, Cortex, Deep Brain, …)
 *     - brainBounds (camera framing)
 *
 * Rules enforced:
 *  1. Every conceptId in a group MUST exist in atlas.concepts.
 *     The Brain Mode UI filters out missing concepts at render time, so
 *     the panel never shows an empty group.
 *  2. Brain ventricles (FMA78448 lateral ventricle, FMA78454 third
 *     ventricle, FMA78469 fourth ventricle, etc.) live in the
 *     `ventricular-system` group. They are classified as `cardiac` in the
 *     source but are normalized to `nervous` via the KYP normalization
 *     layer. See kyp-normalization.ts.
 *  3. No group is created that has no real atlas concepts behind it.
 *  4. Substantia nigra is NOT in this registry — BodyParts3D does not
 *     provide a mesh for it. Pathway / disorder content may still
 *     reference it conceptually via the KYP data layer, but it is never
 *     shown as a selectable 3D structure.
 */

export interface BrainStructureGroup {
  id: string;
  label: string;
  /**
   * FMA concept IDs that belong to this group.
   * Every ID MUST exist in atlas.concepts — concepts that don't exist
   * are filtered out at render time, and the group is hidden if no
   * concepts remain.
   */
  conceptIds: string[];
  /** Brief description for the UI */
  description: string;
}

export interface BrainPreset {
  id: string;
  label: string;
  description: string;
  /** Groups to show when this preset is active */
  groupIds: string[];
}

/**
 * Brain structure groups.
 *
 * Each group is a KYP navigation grouping, not a formal anatomical
 * ontology. The grouping reflects how a clinician or student would
 * navigate the brain, not the FMA hierarchy.
 *
 * Named lobes (Frontal Cortex, Temporal Cortex, …) are explicitly
 * navigation groups — they collect actual gyri that exist in the source
 * data, rather than fabricating a single "Frontal Lobe" mesh that the
 * source does not provide.
 */
// GENERATED by scripts/anatomy/gen_brain_groups.py from public/models/atlas.json. Edit the rules there.
// GENERATED by scripts/anatomy/gen_brain_groups.py from public/models/atlas.json. Edit the rules there.
// GENERATED by scripts/anatomy/gen_brain_groups.py from public/models/atlas.json. Edit the rules there.
export const brainStructureGroups: BrainStructureGroup[] = [
  {
    id: "frontal-cortex",
    label: "Frontal Cortex",
    description: "Frontal gyri: executive function, motor control, language",
    conceptIds: [
      "ZA-left-opercular-part-of-inferior-frontal-gyrus", "ZA-left-orbital-part-of-inferior-frontal-gyrus", "ZA-left-triangular-part-of-inferior-frontal-gyrus",
      "ZA-left-orbital-gyri-frontomarginal-gyrus-and-sulcus", "ZA-left-paracentral-gyrus-and-sulcus", "ZA-left-transverse-frontopolar-gyrus-and-sulcus",
      "ZA-left-straight-gyrus-gyrus-rectus", "ZA-left-middle-frontal-gyrus", "ZA-left-orbital-gyri",
      "ZA-left-precentral-gyrus", "ZA-left-superior-frontal-gyrus", "ZA-right-opercular-part-of-inferior-frontal-gyrus",
      "ZA-right-triangular-part-of-inferior-frontal-gyrus", "ZA-right-orbital-gyri-frontomarginal-gyrus-and-sulcus", "ZA-right-paracentral-gyrus-and-sulcus",
      "ZA-right-transverse-frontopolar-gyrus-and-sulcus", "ZA-right-straight-gyrus-gyrus-rectus", "ZA-right-orbital-part-of-inferior-frontal-gyrus",
      "ZA-right-middle-frontal-gyrus", "ZA-right-orbital-gyri", "ZA-right-precentral-gyrus",
      "ZA-right-superior-frontal-gyrus",
    ],
  },
  {
    id: "parietal-cortex",
    label: "Parietal Cortex",
    description: "Parietal gyri: somatosensory processing, spatial orientation",
    conceptIds: [
      "ZA-left-angular-gyrus", "ZA-left-supramarginal-gyrus", "ZA-left-postcentral-gyrus",
      "ZA-left-precuneus", "ZA-right-angular-gyrus", "ZA-right-supramarginal-gyrus",
      "ZA-right-postcentral-gyrus", "ZA-right-precuneus",
    ],
  },
  {
    id: "temporal-cortex",
    label: "Temporal Cortex",
    description: "Temporal gyri: auditory processing, memory, language",
    conceptIds: [
      "ZA-left-temporal-pole", "ZA-left-transverse-temporal-gyri", "ZA-left-temporal-plane",
      "ZA-left-superior-temporal-gyrus-lateral-part", "ZA-left-lateral-occipitotemporal-gyrus", "ZA-left-inferior-temporal-gyrus",
      "ZA-left-middle-temporal-gyrus", "ZA-right-temporal-pole", "ZA-right-transverse-temporal-gyri",
      "ZA-right-temporal-plane", "ZA-right-superior-temporal-gyrus-lateral-part", "ZA-right-lateral-occipitotemporal-gyrus",
      "ZA-right-inferior-temporal-gyrus", "ZA-right-middle-temporal-gyrus",
    ],
  },
  {
    id: "occipital-cortex",
    label: "Occipital Cortex",
    description: "Occipital gyri: visual processing",
    conceptIds: [
      "ZA-left-occipital-pole", "ZA-left-inferior-occipital-gyrus-and-sulcus", "ZA-left-lingual-gyrus",
      "ZA-left-lateral-occipital-gyrus-middle-occipital-gyrus", "ZA-left-cuneus", "ZA-left-superior-occipital-gyri",
      "ZA-right-occipital-pole", "ZA-right-inferior-occipital-gyrus-and-sulcus", "ZA-right-lingual-gyrus",
      "ZA-right-lateral-occipital-gyrus-middle-occipital-gyrus", "ZA-right-cuneus", "ZA-right-superior-occipital-gyri",
    ],
  },
  {
    id: "other-cortex",
    label: "Other Cortical Structures",
    description: "Cingulate gyrus, insula and the anterior commissure",
    conceptIds: [
      "ZA-anterior-commissure", "ZA-left-circular-sulcus-of-insula", "ZA-right-circular-sulcus-of-insula",
      "ZA-left-insula-subcentral-gyrus-and-ant-and-post-sulci", "ZA-right-insula-subcentral-gyrus-and-ant-and-post-sulci", "ZA-left-cingulate-gyrus-and-sulcus-middle-anterior-part",
      "ZA-left-cingulate-gyrus-and-sulcus-middle-posterior-part", "ZA-left-cingulate-gyrus-and-sulcus-posterior-dorsal-part", "ZA-left-cingulate-gyrus-posteroventral-part",
      "ZA-right-cingulate-gyrus-and-sulcus-middle-anterior-part", "ZA-right-cingulate-gyrus-and-sulcus-middle-posterior-part", "ZA-right-cingulate-gyrus-and-sulcus-posterior-dorsal-part",
      "ZA-right-cingulate-gyrus-posteroventral-part",
    ],
  },
  {
    id: "thalamus",
    label: "Thalamus",
    description: "Sensory relay station and motor integration",
    conceptIds: [
      "ZA-right-thalamus", "ZA-left-thalamus", "ZA-hypothalamus",
      "ZA-right-lateral-geniculate-body", "ZA-right-medial-geniculate-body", "ZA-left-lateral-geniculate-body",
      "ZA-left-medial-geniculate-body",
    ],
  },
  {
    id: "hypothalamus",
    label: "Hypothalamus",
    description: "Hormonal regulation, autonomic control, circadian rhythm",
    conceptIds: [
      "ZA-left-mamillary-body", "ZA-right-mamillary-body",
    ],
  },
  {
    id: "basal-ganglia",
    label: "Basal Ganglia",
    description: "Caudate, putamen, globus pallidus: motor control and reward",
    conceptIds: [
      "ZA-right-globus-pallidus", "ZA-left-globus-pallidus", "ZA-right-lentiform-nucleus",
      "ZA-left-lentiform-nucleus", "ZA-right-putamen", "ZA-left-putamen",
    ],
  },
  {
    id: "limbic-system",
    label: "Limbic System",
    description: "Hippocampus, amygdala, fornix and septal structures: memory and emotion",
    conceptIds: [
      "ZA-right-stria-terminalis", "ZA-left-stria-terminalis", "ZA-hippocampal-commissure",
      "ZA-right-fornix", "ZA-left-fornix", "ZA-right-amygdaloid-body",
      "ZA-left-amygdaloid-body", "ZA-septal-nuclei", "ZA-left-medial-occipitotemporal-gyrus-parahippocampal",
      "ZA-right-medial-occipitotemporal-gyrus-parahippocampal", "ZA-right-hippocampus", "ZA-left-hippocampus",
      "ZA-septum-pellucidum", "ZA-habenula",
    ],
  },
  {
    id: "corpus-callosum",
    label: "Corpus Callosum",
    description: "Connects the two cerebral hemispheres",
    conceptIds: [
      "ZA-corpus-callosum",
    ],
  },
  {
    id: "white-matter",
    label: "White Matter",
    description: "White matter of the cerebral hemispheres",
    conceptIds: [
      "ZA-left-white-matter-of-telencephalon", "ZA-right-white-matter-of-telencephalon",
    ],
  },
  {
    id: "brainstem",
    label: "Brainstem",
    description: "Pons and medulla: relay, autonomic control and cranial nerve nuclei",
    conceptIds: [
      "ZA-left-vestibular-nuclei", "ZA-right-vestibular-nuclei", "ZA-left-superior-salivatory-nucleus",
      "ZA-right-superior-salivatory-nucleus", "ZA-right-pons", "ZA-left-pons",
      "ZA-left-pyramid-of-medulla-oblongata", "ZA-left-olive", "ZA-left-medulla-oblongata",
      "ZA-right-olive", "ZA-right-pyramid-of-medulla-oblongata", "ZA-left-anterior-cochlear-nucleus",
      "ZA-right-anterior-cochlear-nucleus", "ZA-left-posterior-cochlear-nucleus", "ZA-right-inferior-salivatory-nucleus",
      "ZA-right-posterior-cochlear-nucleus", "ZA-left-posterior-nucleus-of-vagus-nerve", "ZA-left-nucleus-of-hypoglossal-nerve",
      "ZA-right-posterior-nucleus-of-vagus-nerve", "ZA-right-nucleus-of-hypoglossal-nerve", "ZA-right-nucleus-ambiguus",
      "ZA-left-nucleus-ambiguus", "ZA-left-inferior-salivatory-nucleus", "ZA-right-medulla-oblongata",
      "ZA-right-nucleus-of-accessory-nerve", "ZA-left-nucleus-of-accessory-nerve",
    ],
  },
  {
    id: "midbrain",
    label: "Midbrain",
    description: "Midbrain, peduncles and colliculi",
    conceptIds: [
      "ZA-posterior-commissure", "ZA-right-midbrain", "ZA-left-interpeduncular-fossa",
      "ZA-right-interpeduncular-fossa", "ZA-left-midbrain", "ZA-right-base-of-peduncle",
      "ZA-left-base-of-peduncle", "ZA-left-red-nucleus", "ZA-right-red-nucleus",
      "ZA-right-superior-colliculus", "ZA-left-superior-colliculus", "ZA-right-inferior-colliculus",
      "ZA-left-inferior-colliculus",
    ],
  },
  {
    id: "cerebellum",
    label: "Cerebellum",
    description: "Motor coordination, balance and motor learning",
    conceptIds: [
      "ZA-left-superior-parietal-lobule", "ZA-right-superior-parietal-lobule", "ZA-left-wing-of-central-lobule",
      "ZA-uvula-of-vermis", "ZA-tuber-of-vermis", "ZA-left-tonsil-of-cerebellum",
      "ZA-left-superior-semilunar-lobule", "ZA-left-superior-cerebellar-peduncle", "ZA-pyramis-of-vermis",
      "ZA-left-posterior-quadrangular-lobule", "ZA-left-peduncle-of-flocculus", "ZA-nodule-of-vermis",
      "ZA-lingula-of-cerebellum", "ZA-left-inferior-semilunar-lobule", "ZA-left-gracile-lobule",
      "ZA-folium-of-vermis", "ZA-left-flocculus", "ZA-declive",
      "ZA-culmen", "ZA-central-lobule", "ZA-left-biventral-lobule",
      "ZA-left-anterior-quadrangular-lobule", "ZA-right-wing-of-central-lobule", "ZA-right-tonsil-of-cerebellum",
      "ZA-right-superior-semilunar-lobule", "ZA-right-superior-cerebellar-peduncle", "ZA-right-posterior-quadrangular-lobule",
      "ZA-right-peduncle-of-flocculus", "ZA-right-inferior-semilunar-lobule", "ZA-right-gracile-lobule",
      "ZA-right-flocculus", "ZA-right-biventral-lobule", "ZA-right-anterior-quadrangular-lobule",
    ],
  },
  {
    id: "ventricular-system",
    label: "Ventricular System",
    description: "CSF-filled chambers of the brain: lateral, third and fourth ventricles, plus the choroid plexus that makes the fluid",
    conceptIds: [
      "ZA-right-choroid-plexus", "ZA-left-choroid-plexus", "ZA-right-lateral-ventricle",
      "ZA-left-lateral-ventricle", "ZA-third-ventricle", "ZA-fourth-ventricle",
      "ZA-aqueduct-of-midbrain",
    ],
  },
  {
    id: "cranial-nerves",
    label: "Cranial Nerves",
    description: "Olfactory, optic, oculomotor, trochlear, trigeminal, abducens, facial, vestibulocochlear, glossopharyngeal, vagus, accessory and hypoglossal nerves",
    conceptIds: [
      "ZA-right-optic-chiasm", "ZA-left-optic-chiasm", "ZA-left-nucleus-of-abducens-nerve",
      "ZA-right-nucleus-of-abducens-nerve", "ZA-left-motor-nucleus-of-facial-nerve", "ZA-right-motor-nucleus-of-facial-nerve",
      "ZA-left-nucleus-of-trochlear-nerve", "ZA-right-nucleus-of-trochlear-nerve", "ZA-left-nucleus-of-oculomotor-nerve",
      "ZA-right-nucleus-of-oculomotor-nerve", "ZA-right-accessory-nucleus-of-oculomotor-nerve", "ZA-left-accessory-nucleus-of-oculomotor-nerve",
      "ZA-right-olfactory-nerve-i", "ZA-left-olfactory-nerve-i", "ZA-right-optic-nerve-ii",
      "ZA-left-optic-nerve-ii", "ZA-right-oculomotor-nerve-iii", "ZA-left-oculomotor-nerve-iii",
      "ZA-right-sensory-root-of-trigeminal-nerve", "ZA-right-motor-root-of-trigeminal-nerve", "ZA-right-trigeminal-nerve-v",
      "ZA-left-sensory-root-of-trigeminal-nerve", "ZA-left-motor-root-of-trigeminal-nerve", "ZA-left-trigeminal-nerve-v",
      "ZA-right-chorda-tympani", "ZA-right-facial-nerve-vii", "ZA-left-chorda-tympani",
      "ZA-left-facial-nerve-vii", "ZA-left-vestibular-nerve", "ZA-left-cochlear-nerve",
      "ZA-left-vestibulocochlear-nerve-viii", "ZA-cochlear-nerve", "ZA-right-vestibular-nerve",
      "ZA-right-vestibulocochlear-nerve-viii", "ZA-right-glossopharyngeal-nerve-ix", "ZA-left-glossopharyngeal-nerve-ix",
      "ZA-right-vagus-nerve-x", "ZA-left-vagus-nerve-x", "ZA-right-hypoglossal-nerve-xii",
      "ZA-left-hypoglossal-nerve-xii", "ZA-right-abducens-nerve-vi", "ZA-right-trochlear-nerve-iv",
      "ZA-left-abducens-nerve-vi", "ZA-left-trochlear-nerve-iv", "ZA-right-accessory-nerve-xi",
      "ZA-left-accessory-nerve-xi",
    ],
  },
];

/**
 * Brain presets — high-level navigation views.
 *
 * Each preset exposes a curated subset of brain groups. The Brain Mode UI
 * uses presets to focus the camera and limit the visible set of parts.
 *
 * A preset only enables groups that exist in `brainStructureGroups` —
 * there are no "phantom" presets pointing at empty groups.
 */
export const brainPresets: BrainPreset[] = [
  {
    id: "whole-brain",
    label: "Whole Brain",
    description: "All brain structures visible",
    groupIds: brainStructureGroups.map((g) => g.id),
  },
  {
    id: "cortex",
    label: "Cortex",
    description: "Frontal, parietal, temporal, occipital cortical groups + white matter",
    groupIds: [
      "frontal-cortex", "parietal-cortex", "temporal-cortex", "occipital-cortex",
      "other-cortex", "white-matter",
    ],
  },
  {
    id: "deep-brain",
    label: "Deep Brain",
    description: "Thalamus, hypothalamus, basal ganglia, limbic, corpus callosum",
    groupIds: [
      "thalamus", "hypothalamus", "basal-ganglia", "limbic-system", "corpus-callosum",
    ],
  },
  {
    id: "brainstem",
    label: "Brainstem",
    description: "Medulla, pons, midbrain",
    groupIds: ["brainstem", "midbrain"],
  },
  {
    id: "cerebellum",
    label: "Cerebellum",
    description: "Cerebellum",
    groupIds: ["cerebellum"],
  },
  {
    id: "ventricular-system",
    label: "Ventricular System",
    description:
      "CSF chambers of the brain, lateral, third, fourth ventricles, " +
      "interventricular foramen. (Normalized from cardiac → nervous.)",
    groupIds: ["ventricular-system"],
  },
];

/**
 * All concept IDs that the registry considers "brain structures".
 * Used by the Brain Mode search to filter atlas concepts down to brain
 * ones (including the normalized ventricular structures).
 *
 * This set is computed once at module load and is a flat union of every
 * group's conceptIds.
 */
export const ALL_BRAIN_CONCEPT_IDS: ReadonlySet<string> = new Set(
  brainStructureGroups.flatMap((g) => g.conceptIds)
);

/**
 * Look up the brain group a concept belongs to.
 * Returns the first matching group (a concept is only ever in one group
 * in the current registry).
 */
export function getBrainGroupForConcept(
  conceptId: string
): BrainStructureGroup | undefined {
  return brainStructureGroups.find((g) => g.conceptIds.includes(conceptId));
}

// ── Camera framing for Brain Mode ────────────────────────────────────────
//
// These values describe the bounding region the brain occupies in
// BodyParts3D model space. The brain sits roughly at y ∈ [1.52, 1.72]
// (the model uses meters, with the feet at y≈0 and the top of the head
// at y≈1.78). The brain's x and z extents are tighter — roughly ±8cm
// in x and −12cm..+9cm in z.
//
// These are used by the camera rig to frame Brain Mode and by the Brain
// Mode panel to show a small "framing" hint. They do NOT affect what is
// rendered.

export const brainBounds = {
  min: [-0.08, 1.52, -0.12],
  max: [0.08, 1.72, 0.09],
  center: [0, 1.62, -0.01] as [number, number, number],
  size: [0.16, 0.20, 0.21],
};

/**
 * Camera positions for brain-specific views.
 * Closer than the full-body views because the brain is small.
 */
export const brainCameraPositions: Record<string, [number, number, number]> = {
  anterior: [0, 1.62, 0.8],
  posterior: [0, 1.62, -0.8],
  left: [-0.8, 1.62, 0],
  right: [0.8, 1.62, 0],
  superior: [0, 2.5, 0.01],
  inferior: [0, 0.8, 0.01],
};
