/**
 * KYP Mechanism System — pilot definitions (Phase C).
 *
 * FIVE hand-authored rich graphs. Every string is traceable to the locked
 * source data (file + field cited per node/edge); compositions and
 * normalisations are recorded in reports/mechanism-pilot-integrity.json
 * (generated by scripts/mechanism-pilot-integrity.ts) — nothing is invented.
 *
 * Pilots are NOT permission to expand the medical corpus (spec §20).
 */

import type { MechanismDefinition } from "./model";
import { validateMechanism } from "./validate";

/* ============================================================
   1. Escitalopram (drug) — src/lib/kyp/data/drugs/escitalopram.ts
      mechanismFlow nodes/edges + mechanism.steps (L59-63) + effect
   ============================================================ */

const escitalopram: MechanismDefinition = validateMechanism({
  mechanismId: "pilot-escitalopram",
  topicId: "escitalopram",
  topicKind: "drug",
  title: "Escitalopram: selective serotonin reuptake inhibition",
  summary:
    "Escitalopram selectively blocks the serotonin transporter (SERT) with the highest selectivity ratio among SSRIs, increasing synaptic serotonin and (over 2–6 weeks) producing downstream neuroadaptive antidepressant and anxiolytic effects.",
  migration: "fully-mapped",
  accessibility: {
    summary:
      "Mechanism diagram of escitalopram, a selective serotonin reuptake inhibitor: SERT blockade raises synaptic serotonin within hours; 5-HT1A autoreceptor desensitisation over days 7 to 14 increases throughput to the prefrontal cortex; BDNF-mediated neurogenesis completes the clinical effect over weeks 2 to 6.",
  },
  compartments: [
    { id: "presynaptic", label: "Presynaptic neuron (raphe)" },
    { id: "cleft", label: "Synaptic cleft" },
    { id: "postsynaptic", label: "Postsynaptic cortex" },
  ],
  nodes: [
    { id: "presynaptic", label: "Presynaptic neuron", sublabel: "Raphe nuclei: synthesises serotonin", type: "cell", level: "cellular", compartmentId: "presynaptic" },
    { id: "serotonin", label: "Serotonin (5-HT)", sublabel: "Released into synaptic cleft", type: "neurotransmitter", level: "molecular", compartmentId: "cleft" },
    { id: "sert", label: "SERT transporter", sublabel: "Normally reuptakes serotonin", type: "transporter", level: "molecular", compartmentId: "presynaptic" },
    { id: "escitalopram", label: "Escitalopram (S-enantiomer)", sublabel: "Highly selective SERT blockade", type: "drug", level: "molecular" },
    { id: "cleft", label: "↑ Synaptic 5-HT", sublabel: "More serotonin available", type: "molecule", level: "molecular", compartmentId: "cleft" },
    { id: "autoreceptor", label: "5-HT1A autoreceptor", sublabel: "Initially brakes firing", type: "receptor", level: "cellular", compartmentId: "presynaptic" },
    { id: "desensitised", label: "Autoreceptors desensitise", sublabel: "Days 7–14: brake removed", type: "receptor", level: "cellular", compartmentId: "presynaptic" },
    { id: "pfc", label: "Prefrontal cortex", sublabel: "Mood regulation improves", type: "organ", level: "organ", compartmentId: "postsynaptic" },
    { id: "bdnf", label: "↑ BDNF + neurogenesis", sublabel: "Weeks 2–6: full effect", type: "protein", level: "molecular", compartmentId: "postsynaptic" },
  ],
  edges: [
    { from: "presynaptic", to: "serotonin", relationship: "releases", label: "releases" },
    { from: "serotonin", to: "sert", relationship: "transports", label: "reuptake" },
    { from: "escitalopram", to: "sert", relationship: "inhibits", label: "blocks (highly selective)", interventionId: "iv-esc-sert" },
    { from: "serotonin", to: "cleft", relationship: "increases", label: "accumulates" },
    { from: "cleft", to: "autoreceptor", relationship: "binds", label: "detects" },
    { from: "autoreceptor", to: "desensitised", relationship: "leads_to", label: "over 7–14 days" },
    { from: "desensitised", to: "pfc", relationship: "increases", label: "increased throughput" },
    { from: "pfc", to: "bdnf", relationship: "leads_to", label: "weeks 2–6" },
    { from: "autoreceptor", to: "presynaptic", relationship: "negative_feedback", label: "inhibit further serotonin release" },
  ],
  feedbackLoops: [
    {
      edgeIds: ["e-autoreceptor-presynaptic-8"],
      direction: "negative",
      label: "Autoreceptor brake (desensitises over 7–14 days)",
    },
  ],
  timeline: [
    { id: "acute", label: "Acute (hours)", nodeIds: ["presynaptic", "serotonin", "sert", "escitalopram", "cleft"] },
    { id: "desens", label: "Autoreceptor desensitisation", range: "days 7–14", nodeIds: ["autoreceptor", "desensitised"] },
    { id: "adapt", label: "Neuroadaptive effects", range: "weeks 2–6", nodeIds: ["pfc", "bdnf"] },
  ],
  interventions: [
    {
      id: "iv-esc-sert",
      agentLabel: "Escitalopram (S-enantiomer)",
      action: "reuptake-inhibition",
      targetId: "sert",
      effectLabel: "blocks (highly selective)",
      description: "Escitalopram selectively blocks the serotonin transporter (SERT) with the highest selectivity ratio among SSRIs.",
    },
  ],
  evidence: {
    grade: "established",
    summary: "SSRI mechanism with well-characterised acute and delayed components.",
    sources: ["src/lib/kyp/data/drugs/escitalopram.ts — mechanismFlow, mechanism.steps, mechanism.effect, mechanism.summary"],
  },
});

/* ============================================================
   2. Aripiprazole (drug) — src/lib/kyp/data/drugs/aripiprazole.ts
      mechanismFlow (7 nodes / 7 edges, labels verbatim)
   ============================================================ */

const aripiprazole: MechanismDefinition = validateMechanism({
  mechanismId: "pilot-aripiprazole",
  topicId: "aripiprazole",
  topicKind: "drug",
  title: "Aripiprazole: D2/D3 partial agonist across four pathways",
  summary:
    "Aripiprazole is a D2/D3 partial agonist with 5-HT2A antagonism and 5-HT1A partial agonism: high-affinity occupancy of D2 receptors yields net antagonism in hyperdopaminergic pathways while preserving tuberoinfundibular prolactin regulation and supporting hypodopaminergic mesocortical tone.",
  migration: "fully-mapped",
  accessibility: {
    summary:
      "Mechanism diagram of aripiprazole, a dopamine D2 and D3 partial agonist: in the mesolimbic pathway with high dopamine tone the drug occupies D2 receptors and produces net antagonism; in the tuberoinfundibular pathway net agonism preserves prolactin regulation; in the mesocortical pathway net agonism supports low-tone regions; 5-HT2A antagonism plus 5-HT1A partial agonism enhances cortical dopamine release.",
  },
  nodes: [
    { id: "drug", label: "Aripiprazole", sublabel: "D2/D3 partial agonist", type: "drug", level: "molecular" },
    { id: "d2", label: "D2 receptor", sublabel: "High-affinity partial agonist occupancy", type: "receptor", level: "molecular" },
    { id: "meso", label: "Mesolimbic pathway", sublabel: "Excess dopamine → psychosis", type: "pathway", level: "systemic" },
    { id: "block", label: "Net antagonism here", sublabel: "Partial agonist out-competes dopamine", type: "physiological-process", level: "clinical" },
    { id: "tuber", label: "Tuberoinfundibular pathway", sublabel: "Prolactin regulation preserved", type: "pathway", level: "systemic" },
    { id: "meso_c", label: "Mesocortical pathway", sublabel: "Agonist support where DA tone is low", type: "pathway", level: "systemic" },
    { id: "5ht2a", label: "5-HT2A antagonism + 5-HT1A partial agonism", sublabel: "Cortical DA release, antidepressant effect", type: "receptor", level: "molecular" },
  ],
  edges: [
    { from: "meso", to: "d2", relationship: "stimulates", label: "high DA tone" },
    { from: "drug", to: "d2", relationship: "binds", label: "occupies", interventionId: "iv-ari-d2" },
    { from: "d2", to: "block", relationship: "inhibits", label: "net blockade" },
    { from: "drug", to: "tuber", relationship: "activates", label: "net agonism" },
    { from: "drug", to: "meso_c", relationship: "activates", label: "net agonism" },
    { from: "drug", to: "5ht2a", relationship: "modulates", label: "modulates", interventionId: "iv-ari-5ht2a" },
    { from: "5ht2a", to: "meso_c", relationship: "increases", label: "enhances" },
  ],
  branches: [
    { fromId: "drug", pathLabels: ["D2 receptors (mesolimbic)", "tuberoinfundibular", "mesocortical", "5-HT2A / 5-HT1A"] },
  ],
  interventions: [
    {
      id: "iv-ari-d2",
      agentLabel: "Aripiprazole",
      action: "receptor-partial-agonism",
      targetId: "d2",
      effectLabel: "occupies",
      description: "High-affinity partial agonist occupancy; the partial agonist out-competes dopamine where tone is high.",
    },
    {
      id: "iv-ari-5ht2a",
      agentLabel: "Aripiprazole",
      action: "receptor-antagonism",
      targetId: "5ht2a",
      effectLabel: "modulates",
      description: "5-HT2A antagonism plus 5-HT1A partial agonism enhances cortical dopamine release.",
    },
  ],
  evidence: {
    grade: "established",
    summary: "Receptor-level pharmacology with pathway-dependent net effects.",
    sources: ["src/lib/kyp/data/drugs/aripiprazole.ts — mechanismFlow"],
  },
});

/* ============================================================
   3. Major depressive disorder (disease)
      src/lib/kyp/data/diseases/major-depressive-disorder.ts
      — summary (L46), etiology.models (L98-104), pathophysiology
      (L147-181), receptors (L188-195), brainRegions/knowledgeGraph
      (L1415-1421), management ketamine entry (L496-501)
   ============================================================ */

const majorDepressiveDisorder: MechanismDefinition = validateMechanism({
  mechanismId: "pilot-major-depressive-disorder",
  topicId: "major-depressive-disorder",
  topicKind: "disease",
  title: "Major depressive disorder: multifactorial pathophysiology",
  summary:
    "Depression involves dysregulation of monoamine neurotransmitters (serotonin, norepinephrine, dopamine), HPA axis hyperactivity, reduced BDNF, and hippocampal volume loss: produced by genetic, neurodevelopmental, inflammatory, and psychosocial factors acting on a vulnerable brain.",
  migration: "fully-mapped",
  accessibility: {
    summary:
      "Disease mechanism diagram of major depressive disorder: monoamine dysregulation, HPA axis hyperactivity with cortisol hypersecretion and impaired feedback, stress-driven reduction of BDNF with hippocampal volume loss, glutamatergic and inflammatory contributions, and circuit-level changes in the amygdala, prefrontal cortex, and subgenual anterior cingulate; SSRI and ketamine interventions shown at their points of action.",
  },
  compartments: [
    { id: "synapse", label: "Synapse & plasticity" },
    { id: "hpa", label: "HPA axis" },
    { id: "circuit", label: "Cortical circuits" },
  ],
  nodes: [
    { id: "stress", label: "Chronic stress", sublabel: "acting on a vulnerable brain", type: "physiological-process", level: "systemic" },
    { id: "monoamine", label: "Monoamine dysregulation", sublabel: "Serotonin, norepinephrine, dopamine", type: "physiological-process", level: "molecular", compartmentId: "synapse" },
    { id: "sert", label: "SERT (serotonin transporter)", sublabel: "target of SSRIs", type: "transporter", level: "molecular", compartmentId: "synapse" },
    { id: "hypothalamus", label: "Hypothalamus", type: "organ", level: "organ", compartmentId: "hpa" },
    { id: "pituitary", label: "Pituitary", type: "organ", level: "organ", compartmentId: "hpa" },
    { id: "adrenal", label: "Adrenal", type: "organ", level: "organ", compartmentId: "hpa" },
    { id: "cortisol", label: "Cortisol hypersecretion", sublabel: "cortisol elevation in ~50% of MDD", type: "molecule", level: "molecular", compartmentId: "hpa" },
    { id: "bdnf", label: "BDNF expression", sublabel: "reduced in depression; restored by all antidepressants", type: "protein", level: "molecular", compartmentId: "synapse" },
    { id: "hippocampus", label: "Hippocampal volume loss", sublabel: "5–10% volume loss in recurrent MDD", type: "organ", level: "organ" },
    { id: "glutamate", label: "Glutamate", sublabel: "excitotoxicity in chronic stress; target of ketamine", type: "neurotransmitter", level: "molecular", compartmentId: "synapse" },
    { id: "nmda", label: "NMDA receptor", sublabel: "target of ketamine/esketamine", type: "receptor", level: "molecular", compartmentId: "synapse" },
    { id: "neuroplasticity", label: "Synaptic plasticity", type: "physiological-process", level: "cellular", compartmentId: "synapse" },
    { id: "amygdala", label: "Amygdala hyperactivity", sublabel: "heightened threat reactivity", type: "organ", level: "organ", compartmentId: "circuit" },
    { id: "pfc", label: "Prefrontal cortex hypoactivity", sublabel: "impaired top-down regulation", type: "organ", level: "organ", compartmentId: "circuit" },
    { id: "sgacc", label: "Subgenual ACC (Brodmann 25) hyperactivity", sublabel: "deep brain stimulation target", type: "organ", level: "organ", compartmentId: "circuit" },
    { id: "inflammation", label: "Inflammatory activation", sublabel: "elevated CRP, IL-6, TNF-α; inflammation activates IDO, shunting tryptophan toward kynurenine", type: "physiological-process", level: "molecular" },
    { id: "syndrome", label: "MDD syndrome", sublabel: "at least 2 weeks of pervasive low mood or loss of interest (anhedonia)", type: "clinical-finding", level: "clinical", role: "endpoint" },
  ],
  edges: [
    { from: "hypothalamus", to: "pituitary", relationship: "activates", label: "HPA axis" },
    { from: "pituitary", to: "adrenal", relationship: "activates", label: "HPA axis" },
    { from: "adrenal", to: "cortisol", relationship: "secretes", label: "cortisol hypersecretion" },
    { from: "cortisol", to: "hippocampus", relationship: "decreases", label: "chronic cortisol damages hippocampal neurons" },
    { from: "cortisol", to: "hypothalamus", relationship: "negative_feedback", label: "impaired dexamethasone suppression" },
    { from: "hippocampus", to: "hypothalamus", relationship: "positive_feedback", label: "glucocorticoid cascade hypothesis" },
    { from: "stress", to: "bdnf", relationship: "decreases", label: "stress and depression lower BDNF expression" },
    { from: "stress", to: "glutamate", relationship: "increases", label: "excitotoxicity in chronic stress" },
    { from: "bdnf", to: "hippocampus", relationship: "leads_to", label: "dendritic atrophy and reduced neurogenesis" },
    { from: "nmda", to: "glutamate", relationship: "leads_to", label: "antagonism → glutamate surge" },
    { from: "glutamate", to: "neuroplasticity", relationship: "leads_to", label: "synaptic plasticity" },
    { from: "neuroplasticity", to: "bdnf", relationship: "leads_to", label: "BDNF release" },
    { from: "monoamine", to: "syndrome", relationship: "leads_to", label: "deficient serotonergic and noradrenergic signalling", qualifier: "proposed" },
    { from: "sert", to: "monoamine", relationship: "transports", label: "raising synaptic monoamines" },
    { from: "hippocampus", to: "syndrome", relationship: "associated_with", label: "greater loss correlating with longer untreated illness" },
    { from: "amygdala", to: "syndrome", relationship: "associated_with", label: "heightened threat reactivity" },
    { from: "pfc", to: "syndrome", relationship: "associated_with", label: "impaired top-down regulation" },
    { from: "sgacc", to: "syndrome", relationship: "associated_with", label: "hyperactive in MDD" },
    { from: "inflammation", to: "syndrome", relationship: "associated_with", label: "high-inflammatory phenotype in treatment-resistant depression" },
    { from: "glutamate", to: "sgacc", relationship: "modulates", label: "altered glutamatergic tone" },
  ],
  feedbackLoops: [
    { edgeIds: ["e-cortisol-hypothalamus-4"], direction: "negative", label: "Impaired HPA negative feedback" },
    { edgeIds: ["e-hippocampus-hypothalamus-5"], direction: "positive", label: "Glucocorticoid cascade (vicious cycle)" },
  ],
  interventions: [
    {
      id: "iv-mdd-ssris",
      agentLabel: "SSRIs (first-line)",
      action: "reuptake-inhibition",
      targetId: "sert",
      effectLabel: "target of SSRIs",
      description: "SSRIs/SNRIs work by raising synaptic monoamines; acute monoamine elevation occurs within hours but clinical effect takes 4–6 weeks.",
    },
    {
      id: "iv-mdd-ketamine",
      agentLabel: "Ketamine / esketamine",
      action: "receptor-antagonism",
      targetId: "nmda",
      effectLabel: "NMDA receptor antagonism",
      description: "NMDA receptor antagonism → glutamate surge → synaptic plasticity and BDNF release. Single IV dose produces response within hours (vs 4–6 weeks for SSRIs).",
    },
  ],
  normalState: {
    label: "Normal state",
    findings: [
      { label: "Monoamines", direction: "normal", text: "balanced serotonergic and noradrenergic signalling" },
      { label: "HPA axis", direction: "normal", text: "proportionate cortisol response" },
      { label: "BDNF", direction: "normal", text: "BDNF levels maintained; antidepressants of all classes converge on upregulating BDNF" },
      { label: "Hippocampus", direction: "normal", text: "hippocampal volume preserved" },
    ],
  },
  abnormalState: {
    label: "Disease state",
    findings: [
      { label: "Monoamines", direction: "deficiency", text: "monoamine dysregulation (serotonin, norepinephrine, dopamine)" },
      { label: "Cortisol", direction: "accumulation", text: "HPA axis hyperactivity; cortisol elevation in ~50% of MDD with impaired dexamethasone suppression" },
      { label: "BDNF", direction: "decrease", text: "reduced BDNF expression in the hippocampus and prefrontal cortex" },
      { label: "Hippocampus", direction: "loss", text: "volume reduced ~5–10% in recurrent MDD (MRI)" },
      { label: "Amygdala / PFC / sgACC", direction: "increase", text: "hyperactive amygdala, hypoactive prefrontal cortex, hyperactive subgenual cingulate" },
      { label: "Inflammation", direction: "increase", text: "elevated CRP, IL-6, TNF-α" },
    ],
  },
  clinicalConsequences: [
    { label: "Treatment response", description: "With appropriate treatment, 60–70% of patients achieve response and 30–40% achieve remission." },
    { label: "Untreated risk", description: "Untreated, MDD carries significant morbidity and a 4–10% completed-suicide rate." },
  ],
  scenarios: [
    {
      id: "sc-sert",
      question: "What happens if SERT is inhibited?",
      answer: "Acute monoamine elevation occurs within hours but clinical effect takes 4–6 weeks, pointing to downstream adaptive changes (5-HT1A autoreceptor desensitisation, BDNF upregulation, receptor downregulation) as the true therapeutic mechanism.",
      focusNodeIds: ["sert", "monoamine", "bdnf"],
    },
    {
      id: "sc-nmda",
      question: "What happens if NMDA receptors are blocked?",
      answer: "NMDA receptor antagonism → glutamate surge → synaptic plasticity and BDNF release. Single IV dose produces response within hours (vs 4–6 weeks for SSRIs).",
      focusNodeIds: ["nmda", "glutamate", "neuroplasticity", "bdnf"],
    },
    {
      id: "sc-bdnf",
      question: "What happens if BDNF is deficient?",
      answer: "Stress and depression reduce BDNF expression in the hippocampus and prefrontal cortex, producing dendritic atrophy and reduced neurogenesis; hippocampal volume is reduced ~5–10% in recurrent MDD.",
      focusNodeIds: ["bdnf", "hippocampus"],
    },
  ],
  evidence: {
    grade: "supported",
    summary:
      "The monoamine hypothesis is incomplete: MDD is a network disorder with three converging hypotheses (monoamine, BDNF/neuroplasticity, inflammatory) plus HPA and circuit-level changes.",
    sources: [
      "src/lib/kyp/data/diseases/major-depressive-disorder.ts — summary, etiology.models, pathophysiology.{summary,neurotransmitters,pathways,details}, receptors, knowledgeGraph nodes, management (ketamine entry)",
    ],
  },
});

/* ============================================================
   4. Disulfiram (substance treatment) — src/lib/kyp/data/substances/alcohol.ts
      treatment.medications[Disulfiram].mechanismFlow (5 steps, L317+) +
      reactionSymptoms; drug-page flow (drugs/disulfiram.ts) is the
      COLLISION counterpart handled separately by the adapter.
   ============================================================ */

const disulfiram: MechanismDefinition = validateMechanism({
  mechanismId: "pilot-alcohol-disulfiram",
  topicId: "alcohol",
  topicKind: "substance",
  title: "Disulfiram: aldehyde dehydrogenase inhibition (alcohol treatment)",
  summary:
    "Disulfiram inhibits aldehyde dehydrogenase enzyme; alcohol ingestion while on disulfiram therapy leads to toxic acetaldehyde accumulation and the disulfiram reaction.",
  migration: "fully-mapped",
  accessibility: {
    summary:
      "Mechanism diagram of the disulfiram reaction: alcohol is converted by alcohol dehydrogenase to acetaldehyde normally; disulfiram blocks aldehyde dehydrogenase so toxic acetaldehyde accumulates in the bloodstream, producing flushing, tachycardia, nausea, vomiting and anxiety.",
  },
  nodes: [
    { id: "ingestion", label: "Alcohol Ingestion", sublabel: "Patient consumes alcohol while on disulfiram therapy", type: "molecule", level: "molecular" },
    { id: "acetaldehyde", label: "Acetaldehyde", sublabel: "Alcohol dehydrogenase converts ethanol to acetaldehyde normally", type: "molecule", level: "molecular" },
    { id: "aldh", label: "Aldehyde dehydrogenase (ALDH)", sublabel: "Disulfiram inhibits aldehyde dehydrogenase enzyme", type: "enzyme", level: "molecular" },
    { id: "disulfiram", label: "Disulfiram", sublabel: "works by inhibiting aldehyde dehydrogenase", type: "drug", level: "molecular" },
    { id: "reaction", label: "Disulfiram Reaction", sublabel: "Flushing, tachycardia, nausea, vomiting, anxiety", type: "clinical-finding", level: "clinical", role: "endpoint" },
  ],
  edges: [
    { from: "ingestion", to: "acetaldehyde", relationship: "converts", label: "Alcohol dehydrogenase converts ethanol to acetaldehyde normally" },
    { from: "disulfiram", to: "aldh", relationship: "inhibits", label: "Disulfiram inhibits aldehyde dehydrogenase enzyme", interventionId: "iv-dsf-aldh" },
    { from: "acetaldehyde", to: "reaction", relationship: "leads_to", label: "Toxic acetaldehyde accumulates in the bloodstream" },
  ],
  interventions: [
    {
      id: "iv-dsf-aldh",
      agentLabel: "Disulfiram",
      action: "enzyme-inhibition",
      targetId: "aldh",
      effectLabel: "Disulfiram inhibits aldehyde dehydrogenase enzyme",
      description: "Disulfiram inhibits aldehyde dehydrogenase enzyme, so acetaldehyde from alcohol ingestion accumulates instead of being metabolised.",
    },
  ],
  clinicalConsequences: [
    { label: "Common symptoms", description: "Facial flushing, throbbing headache, nausea and vomiting, tachycardia, hypotension." },
    { label: "Severe symptoms", description: "Respiratory difficulty, chest pain, arrhythmias, confusion, cardiovascular collapse." },
  ],
  evidence: {
    grade: "established",
    summary: "Classical enzyme-inhibition deterrence mechanism.",
    sources: ["src/lib/kyp/data/substances/alcohol.ts — treatment.medications[Disulfiram].mechanismFlow + reactionSymptoms"],
  },
});

/* ============================================================
   5. Naloxone (substance emergency) — src/lib/kyp/data/substances/opioids.ts
      naloxoneInfo.mechanismFlow (5 steps, L329+) + summary +
      pharmacologyNotes
   ============================================================ */

const naloxone: MechanismDefinition = validateMechanism({
  mechanismId: "pilot-opioids-naloxone",
  topicId: "opioids",
  topicKind: "substance",
  title: "Naloxone: competitive antagonism at mu opioid receptors",
  summary:
    "Naloxone is a pure opioid antagonist that rapidly reverses opioid overdose. It has higher affinity for mu opioid receptors than most opioids, displacing them and restoring normal breathing within minutes.",
  migration: "fully-mapped",
  accessibility: {
    summary:
      "Emergency mechanism diagram of naloxone: opioids bound to mu receptors cause respiratory depression; naloxone has higher affinity for mu receptors than opioids and displaces them through receptor competition, reversing effects so breathing resumes within 2 to 5 minutes and consciousness returns.",
  },
  nodes: [
    { id: "overdose", label: "Opioid Overdose", sublabel: "Opioids bound to mu receptors causing respiratory depression", type: "clinical-finding", level: "clinical" },
    { id: "mu", label: "Mu opioid receptors", sublabel: "Naloxone has higher affinity for mu receptors than opioids", type: "receptor", level: "molecular" },
    { id: "naloxone", label: "Naloxone Administered", sublabel: "IV, IM, or intranasal naloxone enters bloodstream rapidly", type: "drug", level: "molecular" },
    { id: "displacement", label: "Opioid Displacement", sublabel: "Naloxone displaces opioids from receptors, reversing effects", type: "physiological-process", level: "molecular" },
    { id: "reversal", label: "Reversal", sublabel: "Breathing resumes within 2-5 minutes. Consciousness returns.", type: "clinical-finding", level: "clinical", role: "endpoint" },
  ],
  edges: [
    { from: "overdose", to: "mu", relationship: "binds", label: "opioids bound to mu receptors" },
    { from: "naloxone", to: "mu", relationship: "displaces", label: "higher affinity for mu receptors than opioids", interventionId: "iv-nlx-mu" },
    { from: "mu", to: "displacement", relationship: "leads_to", label: "receptor competition" },
    { from: "displacement", to: "reversal", relationship: "leads_to", label: "reversing effects" },
  ],
  interventions: [
    {
      id: "iv-nlx-mu",
      agentLabel: "Naloxone",
      action: "competitive-antagonism",
      targetId: "mu",
      effectLabel: "higher affinity, displaces opioids",
      description: "High receptor affinity: binds more tightly than most opioids; competitive antagonism displaces opioids from mu receptors.",
    },
  ],
  clinicalConsequences: [
    { label: "Rapid onset", description: "Works within 2-5 minutes IV, 5-10 minutes IM." },
    { label: "Short half-life", description: "30-81 minutes, may need repeat dosing." },
    { label: "No abuse potential", description: "Pure antagonist with no abuse potential." },
  ],
  evidence: {
    grade: "established",
    summary: "Emergency receptor-competition mechanism with rapid, time-limited action.",
    sources: ["src/lib/kyp/data/substances/opioids.ts — naloxoneInfo.{mechanismFlow,summary,pharmacologyNotes}"],
  },
});

/* ============================================================
   Registry
   ============================================================ */

export const pilotMechanisms: MechanismDefinition[] = [
  escitalopram,
  aripiprazole,
  majorDepressiveDisorder,
  disulfiram,
  naloxone,
];

const byMechanismId = new Map(pilotMechanisms.map((m) => [m.mechanismId, m]));

/**
 * Pilot lookup for DRUG pages. Keys are the drug's own topic slug.
 * Deliberately separate from `getTreatmentPilot` (below) so a substance
 * treatment pilot can never leak onto a drug page or vice versa —
 * the disulfiram collision regression (tests/mechanism-integrity.test.ts).
 */
export function getPilotMechanism(drugSlug: string): MechanismDefinition | null {
  return byMechanismId.get(`pilot-${drugSlug}`) ?? null;
}

/**
 * Pilot lookup for SUBSTANCE treatment flows. Keys are
 * `${substanceSlug}:${medicationName}` pairs from the source data.
 */
export function getTreatmentPilot(substanceSlug: string, medicationName: string): MechanismDefinition | null {
  const key = `pilot-${substanceSlug}-${medicationName.toLowerCase()}`;
  return byMechanismId.get(key) ?? null;
}

/** The disease-page pilot (MDD pathophysiology). */
export function getDiseasePilot(diseaseSlug: string): MechanismDefinition | null {
  return byMechanismId.get(`pilot-${diseaseSlug}`) ?? null;
}
