/**
 * AUTO-GENERATED — KYP Psychiatry study metadata. DO NOT EDIT BY HAND.
 *
 * Generated from the canonical course registry by:
 *   bun run scripts/generate-psychiatry-study-meta.ts
 *
 * One entry per registered psychiatry course: the completable-section
 * total (the D-2 canonical denominator — rendered outline minus the
 * hero "top" anchor). This is the same number the course page, the
 * read tracker and the library rows show, so Study Mode progress
 * fractions can never disagree with them.
 *
 * Static + client-safe on purpose (imported by Study Mode client
 * components; the full registry is too heavy for the browser bundle).
 * Freshness is verified by tests/psychiatry-site.test.ts #88.
 */
export const PSYCHIATRY_COURSE_TOTALS: Record<string, number> = {
  "acute-stress-reaction": 23,
  "acute-transient-psychosis": 23,
  "adhd": 23,
  "adjustment-disorder": 23,
  "alcohol-related-dementia": 23,
  "alcohol-use-disorders": 23,
  "alzheimers-dementia": 23,
  "amnesic-syndromes": 23,
  "anorexia-nervosa": 23,
  "autism": 23,
  "benzodiazepine-misuse": 23,
  "bereavement": 23,
  "bipolar-disorders": 23,
  "bulimia-nervosa": 23,
  "cannabis-mental-health": 23,
  "child-adversity-contexts": 23,
  "child-anxiety": 23,
  "child-assessment-epidemiology": 23,
  "child-neuropsychiatry": 23,
  "child-sleep": 23,
  "child-trauma-abuse": 23,
  "cognitive-assessment": 22,
  "conduct-disorder": 23,
  "couples-therapy": 23,
  "delirium": 23,
  "delusional-disorder": 23,
  "dementia-management": 23,
  "depersonalization-disorder": 23,
  "depressive-disorders": 23,
  "developmental-disorders": 23,
  "dynamic-psychotherapy": 23,
  "elderly-anxiety-ocd": 23,
  "elderly-delirium": 23,
  "elderly-mood": 23,
  "elderly-personality": 23,
  "elderly-substance-use": 23,
  "elderly-suicide": 23,
  "family-therapy": 23,
  "frontotemporal-dementia": 23,
  "gad": 23,
  "gambling-disorder": 23,
  "gender-identity-adults": 23,
  "group-therapy": 23,
  "hallucinogen-use-disorders": 23,
  "hiv-neuropsychiatry": 23,
  "homicide-infanticide": 23,
  "huntingtons-neuropsychiatry": 23,
  "hypersomnia": 23,
  "id-dual-diagnosis": 23,
  "id-syndromes": 23,
  "id-treatment-services": 23,
  "impulse-control-disorders": 23,
  "indigenous-healing": 23,
  "insomnia": 23,
  "intellectual-disability-overview": 23,
  "juvenile-offending": 23,
  "late-life-psychosis": 23,
  "lewy-body-dementia": 23,
  "mci": 23,
  "memory-emotion-science": 23,
  "memory-rehabilitation": 23,
  "mental-health-law": 23,
  "mh-services": 21,
  "neuroendocrinology": 23,
  "neuroimaging": 23,
  "neurotransmitters": 19,
  "nicotine-dependence": 23,
  "ocd": 23,
  "opioid-use-disorders": 23,
  "paediatric-mood": 23,
  "paediatric-ocd-tics": 23,
  "panic-disorder": 23,
  "paraphilias": 23,
  "parasomnias": 23,
  "parkinsons-dementia": 23,
  "party-drug-use-disorders": 23,
  "persistent-mood-disorders": 23,
  "personality-assessment": 23,
  "personality-disorder-treatment": 23,
  "personality-disorder-types": 23,
  "personality-disorders-overview": 23,
  "primary-care-psychiatry": 21,
  "prion-disease": 23,
  "psychiatric-assessment": 23,
  "psychiatric-classification": 23,
  "psychiatric-genetics": 23,
  "psychiatric-phenomenology": 23,
  "psychiatric-rehabilitation": 23,
  "psychiatry-offending": 23,
  "psychodynamic-theories": 23,
  "ptsd": 23,
  "recovered-memories": 20,
  "refugee-mental-health": 21,
  "schizoaffective-schizotypal": 23,
  "schizophrenia": 23,
  "sexual-dysfunctions": 23,
  "sleep-basics": 23,
  "social-anxiety-phobias": 23,
  "speech-language-disorders": 23,
  "stimulant-use-disorders": 23,
  "substance-use-overview": 23,
  "suicide-self-harm": 23,
  "tbi-neuropsychiatry": 23,
  "therapeutic-communities": 23,
  "transcultural-stigma": 21,
  "vascular-dementia": 23,
  "volatile-substance-misuse": 23,
  "voluntary-sector": 21,
  "youth-suicide": 23,
};
